name: Build Installers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - installers/**

# Two jobs, Alpine Multiarch (amd64, arm64), Debian Bun Multiarch (amd64, arm64)

jobs:
  pushMultiArchAlpine:
    name: "yolks:installers_multiarch:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - alpine
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./installers
          file: ./installers/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/otterservers/installers:${{ matrix.tag }}
  pushMultiArchDebianBun:
    name: "yolks:installers_multiarch:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - debian
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./installers
          file: ./installers/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/otterservers/installers:${{ matrix.tag }}
